###Integrantes
#Carlos Eduardo Cardia Fernandez - 11911EMT016
#Gessyca Carneiro Bernandes - 11911EMT022
#Laura Bueno Ferreira - 11911EMT017
#Talles Martins de Carvalho - 11911EMT014

projeto: projeto.c
	gcc -o projeto projeto.c -pthread
